package com.iotplatform.telemetry.model.enums;

public enum AuditAction {
    USER_REGISTERED, USER_LOGGED_IN, USER_ROLE_CHANGED, USER_DEACTIVATED,
    DEVICE_CREATED, DEVICE_UPDATED, DEVICE_DELETED, DEVICE_HEARTBEAT,
    TELEMETRY_INGESTED, TELEMETRY_BATCH_INGESTED,
    RULE_CREATED, RULE_UPDATED, RULE_DELETED,
    ALERT_CREATED, ALERT_RESOLVED, ALERT_DELETED,
    SIMULATION_RUN, WEBHOOK_TRIGGERED
}