package com.iotplatform.model.enums;

public enum AuditAction {
    USER_REGISTERED,
    USER_LOGGED_IN,
    USER_ROLE_CHANGED,
    USER_DEACTIVATED,
    USER_PASSWORD_RESET,

    DEVICE_CREATED,
    DEVICE_UPDATED,
    DEVICE_DELETED,
    DEVICE_STATUS_CHANGED,
    DEVICE_HEARTBEAT,

    ACCESS_GRANTED,
    ACCESS_UPDATED,
    ACCESS_REVOKED,

    TELEMETRY_INGESTED,
    TELEMETRY_BATCH_INGESTED,

    RULE_CREATED,
    RULE_UPDATED,
    RULE_DELETED,
    RULE_TOGGLED,

    ALERT_CREATED,
    ALERT_RESOLVED,
    ALERT_DELETED,

    COMMAND_SENT,
    COMMAND_ACKNOWLEDGED,

    MAINTENANCE_SCHEDULED,
    MAINTENANCE_CANCELLED,

    WEBHOOK_CREATED,
    WEBHOOK_DELETED,
    WEBHOOK_TRIGGERED,

    SIMULATION_RUN
}